M48
; DRILL file {KiCad 6.0.0} date Sat 15 Jan 2022 12:53:04 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-15T12:53:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.9764Y-3.3465
X3.9764Y-4.2913
X5.4331Y-3.3465
X5.4331Y-4.2913
T0
M30
